// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqgixjkisoidgnnbuadd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZ2l4amtpc29pZGdubmJ1YWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzIzNDIsImV4cCI6MjA2NDQ0ODM0Mn0.PIjwMxJYVqAIKYc6qbmyS-15Ai912MlBtDLQSY1eelo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);